*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2058,7 +2058,7 @@ case "${canonical}" in
   i370-ibm-aix*)
     machine=ibm370aix opsys=usg5-3
   ;;
-  s390-*-linux-gnu)
+  s390-*-linux-gnu* )
     machine=ibms390 opsys=gnu-linux
   ;;
   rs6000-ibm-aix3.1* | powerpc-ibm-aix3.1*  )
@@ -2073,7 +2073,7 @@ case "${canonical}" in
   rs6000-ibm-aix4.2* | powerpc-ibm-aix4.2*  )
     machine=ibmrs6000 opsys=aix4-2
   ;;
-  rs6000-ibm-aix5.1* | powerpc-ibm-aix5.1*  )
+  rs6000-ibm-aix5* | powerpc-ibm-aix5*  )
     machine=ibmrs6000 opsys=aix4-2
   ;;
   rs6000-ibm-aix4.0* | powerpc-ibm-aix4.0*  )
@@ -2518,6 +2518,8 @@ case "${canonical}" in
 				OVERRIDE_CPPFLAGS=" "
 				;;
       *-sysv4.2uw* )	  	opsys=unixware; NON_GNU_CPP=/lib/cpp ;;
+      *-sysv5uw* )	  	opsys=unixware; NON_GNU_CPP=/lib/cpp ;;
+      *-sysv5OpenUNIX* )  	opsys=unixware; NON_GNU_CPP=/lib/cpp ;;
       *-386bsd* )	        opsys=386bsd ;;
       *-nextstep* )             opsys=nextstep ;;
       ## Otherwise, we'll fall through to the generic opsys code at the bottom.
@@ -2580,6 +2582,8 @@ if test x"${opsys}" = x; then
     *-sysv2.2 | *-sysvr2.2 )		opsys=usg5-2-2 ;;
     *-sysv3* | *-sysvr3* )		opsys=usg5-3 ;;
     *-sysv4.2uw* )			opsys=unixware ;;
+    *-sysv5uw* )			opsys=unixware ;;
+    *-sysv5OpenUNIX* )			opsys=unixware ;;
     *-sysv4.1* | *-sysvr4.1* )
 	NON_GNU_CPP=/usr/lib/cpp
 	opsys=usg5-4 ;;
@@ -3393,12 +3397,12 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (exit $ac_status); }; }; then
   for ac_declaration in \
    ''\
-   '#include <stdlib.h>' \
    'extern "C" void std::exit (int) throw (); using std::exit;' \
    'extern "C" void std::exit (int); using std::exit;' \
    'extern "C" void exit (int) throw ();' \
    'extern "C" void exit (int);' \
-   'void exit (int);'
+   'void exit (int);' \
+   '#include <stdlib.h>'
 do
   cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -7705,6 +7709,64 @@ fi
 echo "$as_me:$LINENO: result: $HAVE_XFREE386" >&5
 echo "${ECHO_T}$HAVE_XFREE386" >&6
 
+
+case ${host_os} in
+aix*)
+  echo "$as_me:$LINENO: checking for -bbigtoc option" >&5
+echo $ECHO_N "checking for -bbigtoc option... $ECHO_C" >&6
+if test "${gdb_cv_bigtoc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    case $GCC in
+    yes) gdb_cv_bigtoc=-Wl,-bbigtoc ;;
+    *) gdb_cv_bigtoc=-bbigtoc ;;
+    esac
+
+    LDFLAGS=$LDFLAGS\ $gdb_cv_bigtoc
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+int i;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gdb_cv_bigtoc=
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $gdb_cv_bigtoc" >&5
+echo "${ECHO_T}$gdb_cv_bigtoc" >&6
+  ;;
+esac
+
 # Change CFLAGS and CPPFLAGS temporarily so that C_SWITCH_X_SITE gets
 # used for the tests that follow.  We set them back to REAL_CFLAGS and
 # REAL_CPPFLAGS later on.
@@ -10737,7 +10799,8 @@ _ACEOF
 fi
 
 
-# Check for mail-locking functions in a "mail" library
+# Check for mail-locking functions in a "mail" library.  Probably this should
+# have the same check as for liblockfile below.
 
 echo "$as_me:$LINENO: checking for maillock in -lmail" >&5
 echo $ECHO_N "checking for maillock in -lmail... $ECHO_C" >&6
@@ -10915,13 +10978,8 @@ echo "$as_me: error: Shared liblockfile found but can't link against it.
 This probably means that movemail could lose mail.
 There may be a \`development' package to install containing liblockfile." >&2;}
    { (exit 1); exit 1; }; }
-  else
-cat >>confdefs.h <<\_ACEOF
-#define LIBMAIL -llockfile
-_ACEOF
-
-  fi
   else :
+  fi
 fi
 
 for ac_func in touchlock
