Regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9332,6 +9332,51 @@ if test $ac_cv_header_AppKit_AppKit_h = yes; then
 fi
 
 
+  NS_HAVE_INTEGER=yes
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Foundation/NSObjCRuntime.h>
+int
+main ()
+{
+NSInteger i;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ns_have_integer=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ns_have_integer=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  if test $ns_have_integer = no; then
+    NS_HAVE_INTEGER=no
+  fi
 fi
 if test "${HAVE_NS}" = yes; then
   window_system=nextstep
@@ -14849,7 +14894,12 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
   fi
-  # We also have mouse menus.
+
+cat >>confdefs.h <<\_ACEOF
+#define NS_HAVE_INTEGER 1
+_ACEOF
+
+    # We also have mouse menus.
   HAVE_MENUS=yes
 fi
 
@@ -18679,11 +18729,13 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <stdio.h>
+#include <sys/types.h> /* for off_t */
+     #include <stdio.h>
 int
 main ()
 {
-return fseeko (stdin, 0, 0) && (fseeko) (stdin, 0, 0);
+int (*fp) (FILE *, off_t, int) = fseeko;
+     return fseeko (stdin, 0, 0) && fp (stdin, 0, 0);
   ;
   return 0;
 }
@@ -18723,11 +18775,13 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #define _LARGEFILE_SOURCE 1
-#include <stdio.h>
+#include <sys/types.h> /* for off_t */
+     #include <stdio.h>
 int
 main ()
 {
-return fseeko (stdin, 0, 0) && (fseeko) (stdin, 0, 0);
+int (*fp) (FILE *, off_t, int) = fseeko;
+     return fseeko (stdin, 0, 0) && fp (stdin, 0, 0);
   ;
   return 0;
 }
