Added a lot of options to reduce disk size of both the installer and the final application.  Added option to make installer generate self-contained Emacs.app. Now nolonger creates a "full-dist" by default, by omitting .el files that have already been compiled.

diff --git a/mac/make-package b/mac/make-package
--- a/mac/make-package
+++ b/mac/make-package
@@ -40,12 +40,22 @@
 # Contributed by Steven Tamm (steventamm@mac.com).
 
 progname="$0"
-## Default location to place it is /usr/local
 
+srcdir="`pwd`/.."
+builddir=..
+
+## Default location to place it is /usr/local
 prefix=/usr/local
+appsdir=/Applications
+emapp=Emacs.app
 with_config=yes
 with_app=yes
 with_x=no
+comp_diskimage=yes
+self_contained=no
+app_symlink=no
+full_dist=no
+keep_directory=no
 
 ac_prev=
 display_usage=false;
@@ -73,6 +83,14 @@ do
     -with-x | --with-x)
        with_x=yes
        with_app=no ;;
+    --with-full-dist | -with-full-dist | -full-dist | -full)
+       full_dist=yes ;;
+    -self-contained | --with-self-contained-app | -sc)
+       self_contained=yes ;;
+    -app-symlink | --app-symlink | -symlink | --symlink | --asl)
+       app_symlink=yes ;;
+    --keep-dir)
+       keep_directory=yes ;;
     -C,* | -c,*)
        config_options="$config_options `expr "x$1" : 'x[^,]*,\(.*\)'`" ;;
     -M,* | -m,*)
@@ -93,7 +111,8 @@ distribution.  By default, this first runs ./configure on the emacs
 directory.  Then make install to create the emacs distribution.  
 Then some mac-specific commands to generate the required information 
 for the mac package.  The installer will, by default, create a
-Carbon application called Emacs in the /Applications directory, and 
+Carbon application called Emacs in the ${appsdir} directory, with the
+shared emacs files in /usr/local
 
 Usage: $0 [OPTION]
 
@@ -107,6 +126,14 @@ Options:
       --with-x            Setup the install to use X Windows for its 
                           windowed display, instead of carbon.  Implies
                           --without-app.
+      --with-full-dist    Include all the .el files in the distribution.
+                          Default is to include only .elc files 
+      --app-symlink       Have the Emacs.app executable be a symlink
+                          to the install in [prefix]/bin/emacs and have
+                          the emacs executable link to emacs-${version}
+      --self-contained    Create an Emacs.app that is self-contained;
+                          prefix will be ignored and all files installed 
+                          inside the application 
   -C,option               Pass option to configure
   -M,option               Pass option to make
 EOF
@@ -117,7 +144,7 @@ fi
 #set -e
 
 ### Print out each line we read, for debugging's sake.
-set -v
+#set -v
 
 LANGUAGE=C
 LC_ALL=C
@@ -136,8 +163,8 @@ itself.  Move or delete Emacs.pkg and try again." >&2
   exit 1
 fi
 
-if test $with_app == "yes" && [ ! -f Emacs.app/Contents/PkgInfo ]; then
-  echo "${progname}: Can't find \`Emacs.app/Contents/PkgInfo'" >&2
+if test $with_app == "yes" && [ ! -f ${emapp}/Contents/PkgInfo ]; then
+  echo "${progname}: Can't find \`${emapp}/Contents/PkgInfo'" >&2
   echo "${progname} must be run in the \`mac' directory of the Emacs" >&2
   echo "distribution tree.  cd to that directory and try again." >&2
   exit 1
@@ -189,39 +216,77 @@ eject that disc image and try again." >&2
 fi
 
 tempparentfull="`pwd`/${tempparent}"
+tempparentdist=${tempparentfull}/dist
 
 echo Installing into directory ${tempparentfull} >&2
 
-if test "$with_config" = yes; then
-    (cd ..; ./configure ${config_options} --prefix=${prefix};)
+# Run configure in the new tempparent directory
+if test "$with_config" = "yes"; then
+    (cd ..; ./configure ${config_options} --prefix=${prefix})
 fi
 
-## Make bootstrap if .elc files are missing from distribution
-if [ ! -f ../lisp/abbrev.elc ]; then
-   echo "Required .elc files missing; making bootstrap..."
-   if ! (cd ..; make bootstrap prefix=${tempparentfull}${prefix} $make_options); then
-      echo "Make bootstrap failed...  Aborting make-package."
-      exit 2
-   fi
-fi
-
-if ! (cd ..; make install prefix=${tempparentfull}${prefix} $make_options); then
-   echo "Make failed... Aborting make-package."
-   exit 1
+installprefix=${tempparentfull}${prefix}
+if test "$self_contained" = "yes"; then
+    # If selfcontained, the local directory is Resources directory
+    installprefix=$tempparentfull/$appsdir/$emapp/Contents/Resources
 fi
 
 ### This trap ensures that the staging directory will be cleaned up even
 ### when the script is interrupted in mid-career.
 trap "echo 'Interrupted...cleaning up the staging directory'; rm -rf ${tempparent}; rm -rf Emacs.pkg; exit 1" 1 2 15
 
+## Make bootstrap if .elc files are missing from distribution
+if [ ! -f ../lisp/abbrev.elc ]; then
+   echo "Required .elc files missing; making bootstrap..."
+   if ! (cd ${builddir}; make bootstrap prefix=$installprefix $make_options); then
+      echo "Make bootstrap failed...  Aborting make-package."
+      exit 2
+   fi
+fi
+
+if ! (cd ${builddir}; make install prefix=$installprefix $make_options); then
+   echo "Make failed... Aborting make-package."
+   exit 1
+fi
+
+if test "$full_dist" == "no"; then
+    echo "Removing unneeded .el files"
+    sharedir=$installprefix/share/emacs/$version
+    find $sharedir/lisp $sharedir/leim -name "*.elc" -print | sed 's|\(.*\)\.elc$|/bin/rm -f \1.el|' | /bin/sh -s
+fi
+
+if test "$app_symlink" == "yes"; then
+    echo "Replacing bin/emacs with a symbolic link..."
+    # Fix emacs symlink
+    rm ${installprefix}/bin/emacs
+    ln -s $emacsname ${installprefix}/bin/emacs
+fi
+
 if test "$with_app" == "yes"; then
-  mkdir ${tempparentfull}/Applications
+  echo "Creating Emacs.app application"
+  tempappdir=${tempparentfull}${appsdir}
+  mkdir ${tempappdir}
 
   ## Copy Emacs application
-  cp -r Emacs.app ${tempparentfull}/Applications
+  cp -r Emacs.app ${tempappdir}
   ## Delete any CVS files
-  find ${tempparentfull}/Applications -name "CVS" -type d -exec rm -r {} \;
+  find ${tempappdir} -name "CVS" -type d -execdir rm -rf {} \;
+  ## Have application be a symlink to ${prefix}/bin/emacs
+  if test "$app_symlink" == "yes"; then
+    echo "Creating application symlink"
+    tempemapp=${tempappdir}/${emapp}/Contents/MacOS/Emacs
+    rm ${tempemapp}
+    if test "$self_contained" = "yes"; then
+	ln -s ../../Contents/Resources/bin/${emacsname} ${tempemapp}
+    else
+	ln -s ${prefix}/bin/${emacsname} ${tempemapp}
+    fi
+  fi
 fi
+
+# Remove unnecessary .el files
+#if test "$full_dist" = no; then
+#fi
 
 echo "Creating Package Info file"
 
@@ -246,10 +311,15 @@ echo 'UseUserMask NO' >> ${infofile}
 echo 'OverwritePermissions NO' >> ${infofile}
 echo 'InstallFat NO' >> ${infofile}
 
+### Set the install directory to install files as root...  
+### Not sure if this is a good diea
+# echo "Setting owner to root"
+# chown -Rh 0 ${tempparentfull}
+
 echo "Creating pax file"
 (cd ${tempparentfull}; pax -w -f ../Emacs.pkg/Contents/Resources/Emacs.pax .; cd ..)
-#echo "Compressing pax file"
-#gzip Emacs.pkg/Contents/Resources/Emacs.pax
+echo "Compressing pax file"
+gzip Emacs.pkg/Contents/Resources/Emacs.pax
 
 echo "Creating bom file"
 mkbom ${tempparentfull} Emacs.pkg/Contents/Resources/Emacs.bom
@@ -280,12 +350,14 @@ hdiutil eject ${mountLoc}
 echo "Copying Package to Disc Image"
 hdid EmacsRW.dmg
 
-rm -rf ${emacsname}
+if test "$keep_directory" = "no"; then
+    rm -rf ${emacsname}
+fi
 
 if [ ! -d /Volumes/Emacs ]; then
-  echo "Could not create disc image.  The Emacs installer package in this
-directory should be correct.  Please use the Disc Copy program to create
-a disc image." >&2
+  echo "Could not create disc image.  The Emacs installer package (Emacs.pkg)
+in this directory should be correct.  Please use the Disc Copy program to 
+create a disc image." >&2
   exit 0
 fi
 
@@ -295,8 +367,11 @@ cp -R Emacs.pkg /Volumes/Emacs
 echo 'Converting Disc Image to read-only'
 hdiutil eject ${mountLoc}
 hdiutil resize EmacsRW.dmg -sectors min
-hdiutil convert EmacsRW.dmg -format UDRO -o EmacsInstaller.dmg
-gzip EmacsInstaller.dmg
+if test "$comp_diskimage" = "yes"; then
+    hdiutil convert EmacsRW.dmg -format UDZO -imagekey zlib-level=2 -o EmacsInstaller.dmg
+else
+    hdiutil convert EmacsRW.dmg -format UDRO -o EmacsInstaller.dmg
+fi
 rm EmacsRW.dmg
 
 echo "Cleaning up the staging directory"
