(update-elclist): Make errors in final sed non-fatal.

diff --git a/lisp/Makefile.in b/lisp/Makefile.in
--- a/lisp/Makefile.in
+++ b/lisp/Makefile.in
@@ -160,16 +160,18 @@ TAGS TAGS-LISP: $(lisptagsfiles1) $(lisptagsfiles2)
 ## single \ at the end of the replacement text).  For the last line,
 ## just use a single "\", for sed.  Finally, run sed using the command
 ## so constructed and update Makefile.in.  chmod +w is for CVSREAD=1.
+## Errors in final sed are non-fatal, since they have no effect on
+## building Emacs.
 update-elclist:
 	echo "/^ELCFILES/,/^$$/c\\" > temp.sed
 	echo "ELCFILES = \\\\\\" >> temp.sed
 	exclude=`echo $(COMPILE_FIRST) | sed -e 's, ,\\\\|,g' -e 's,\/,\\\\/,g'`; \
 	ls $(lisp)/*.elc $(lisp)/*/*.elc | sed -e "/$$exclude/d" -e "s|^$(lisp)|	\$$(lisp)|" -e 's/$$/ \\\\\\/' -e '$$ s/ \\\\//' >> temp.sed
 	echo "" >> temp.sed
-	sed -f temp.sed $(lisp)/Makefile.in > temp-elcfiles || { rm temp-elcfiles temp.sed; exit 1 ; }
+	-sed -f temp.sed $(lisp)/Makefile.in > temp-elcfiles || rm temp-elcfiles
 	rm temp.sed
 	chmod +w $(lisp)/Makefile.in
-	mv -f temp-elcfiles $(lisp)/Makefile.in
+	mv -f temp-elcfiles $(lisp)/Makefile.in || echo "Maintainer warning: failed to update Makefile.in"
 
 ## Explicitly list the .elc files, for the sake of parallel builds.
 ## http://lists.gnu.org/archive/html/bug-gnu-emacs/2008-05/msg00016.html
